-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 13:44:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema code_nexus_hub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema code_nexus_hub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `code_nexus_hub` DEFAULT CHARACTER SET utf8mb4 ;
USE `code_nexus_hub` ;

-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Customer` (
  `Cust_ID` INT NOT NULL AUTO_INCREMENT,
  `Cust_firstName` VARCHAR(45) NOT NULL,
  `Cust_lastName` VARCHAR(45) NOT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Cust_ID`),
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Brand` (
  `Brand_ID` INT NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Brand_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Manufacturer` (
  `Manufacturer_ID` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Manufacturer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Product` (
  `Product_ID` INT NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Storage` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Qty` INT NOT NULL,
  `Brand_ID` INT NOT NULL,
  `Manufacturer_ID` INT NOT NULL,
  PRIMARY KEY (`Product_ID`),
  INDEX `fk_Product_Brand1_idx` (`Brand_ID` ASC),
  INDEX `fk_Product_Manufacturer1_idx` (`Manufacturer_ID` ASC),
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_ID`)
    REFERENCES `code_nexus_hub`.`Brand` (`Brand_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Manufacturer1`
    FOREIGN KEY (`Manufacturer_ID`)
    REFERENCES `code_nexus_hub`.`Manufacturer` (`Manufacturer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Invoice` (
  `Invoice_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `Product_ID` INT NOT NULL,
  `Qty` INT NOT NULL,
  `Total_Price` DECIMAL(10,2) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Invoice_ID`),
  INDEX `fk_Purchase_Customer_idx` (`Cust_ID` ASC),
  INDEX `fk_Purchase_Product1_idx` (`Product_ID` ASC),
  CONSTRAINT `fk_Purchase_Customer`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Product1`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `code_nexus_hub`.`Product` (`Product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
