-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 12:56:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema code_nexus_hub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema code_nexus_hub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `code_nexus_hub` DEFAULT CHARACTER SET utf8mb4 ;
USE `code_nexus_hub` ;

-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Customer` (
  `Cust_ID` INT NOT NULL AUTO_INCREMENT,
  `Cust_firstName` VARCHAR(45) NOT NULL,
  `Cust_lastName` VARCHAR(45) NOT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Cust_ID`),
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Brand` (
  `Brand_ID` INT NOT NULL,
  `Brand_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Brand_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Product` (
  `Product_ID` INT NOT NULL,
  `Brand_ID` INT NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Storage` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Qty` INT NOT NULL,
  `Product_Name` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Product_ID`),
  INDEX `fk_Product_Brand1_idx` (`Brand_ID` ASC),
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_ID`)
    REFERENCES `code_nexus_hub`.`Brand` (`Brand_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Address` (
  `Address_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `Address_Type` VARCHAR(45) NOT NULL,
  `Customer_Name` VARCHAR(45) NOT NULL,
  `Street_Name` VARCHAR(45) NOT NULL,
  `Apt_Number` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Province` VARCHAR(45) NOT NULL,
  `Postal_Code` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Address_ID`),
  INDEX `fk_Address_Customer1_idx` (`Cust_ID` ASC),
  CONSTRAINT `fk_Address_Customer1`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Orders` (
  `Order_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `Product_ID` INT NOT NULL,
  `Order_Qty` INT NOT NULL,
  `Order_Date` DATE NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Shipping_Method` VARCHAR(45) NOT NULL,
  `Delivery_Date` DATE NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `fk_Orders_Customer1_idx` (`Cust_ID` ASC),
  INDEX `fk_Orders_Product1_idx` (`Product_ID` ASC),
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Product1`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `code_nexus_hub`.`Product` (`Product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Invoice` (
  `Invoice_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Address_ID` INT NOT NULL,
  `Qty` INT NOT NULL,
  `Total_Price` DECIMAL(10,2) NOT NULL,
  `Invoice_Date` DATE NOT NULL,
  `Due_Date` DATE NOT NULL,
  `Shipping_Address` VARCHAR(55) NOT NULL,
  `Sub_Total` DECIMAL(10,2) NOT NULL,
  `Tax_Amount` DECIMAL(10,2) NULL,
  `Shipping_Fee` DECIMAL(10,2) NULL,
  `Total` DECIMAL(10,2) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`Invoice_ID`),
  INDEX `fk_Invoice_Customer1_idx` (`Cust_ID` ASC),
  INDEX `fk_Invoice_Address1_idx` (`Address_ID` ASC),
  INDEX `fk_Invoice_Orders1_idx` (`Order_ID` ASC),
  CONSTRAINT `fk_Invoice_Customer1`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Address1`
    FOREIGN KEY (`Address_ID`)
    REFERENCES `code_nexus_hub`.`Address` (`Address_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Orders1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `code_nexus_hub`.`Orders` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Payment` (
  `Payment_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Payment_Method` VARCHAR(45) NOT NULL,
  `Payment_Date` DATE NOT NULL,
  `Amount` DECIMAL(10,2) NOT NULL,
  `Payment_Status` VARCHAR(45) NOT NULL,
  `Payment_Confirmation` TEXT(15) NOT NULL,
  PRIMARY KEY (`Payment_ID`),
  INDEX `fk_Payment_Customer1_idx` (`Cust_ID` ASC),
  INDEX `fk_Payment_Orders1_idx` (`Order_ID` ASC),
  CONSTRAINT `fk_Payment_Customer1`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Orders1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `code_nexus_hub`.`Orders` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `code_nexus_hub`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `code_nexus_hub`.`Receipt` (
  `Receipt_ID` INT NOT NULL,
  `Invoice_ID` INT NOT NULL,
  `Cust_ID` INT NOT NULL,
  `PaymentDate` DATE NOT NULL,
  `Payment_method` VARCHAR(45) NOT NULL,
  `Amount_Paid` DECIMAL(10,2) NOT NULL,
  `Payment_Status` VARCHAR(45) NOT NULL,
  `Payment_Confirmation` TEXT(15) NOT NULL,
  `Seller_Info` TEXT(50) NOT NULL,
  `Buyer_Info` TEXT(50) NOT NULL,
  `Description_of_Goods` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Receipt_ID`),
  INDEX `fk_Receipt_Invoice1_idx` (`Invoice_ID` ASC),
  INDEX `fk_Receipt_Customer1_idx` (`Cust_ID` ASC),
  CONSTRAINT `fk_Receipt_Invoice1`
    FOREIGN KEY (`Invoice_ID`)
    REFERENCES `code_nexus_hub`.`Invoice` (`Invoice_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_Customer1`
    FOREIGN KEY (`Cust_ID`)
    REFERENCES `code_nexus_hub`.`Customer` (`Cust_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
